/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.accenture.certificacion.despegar;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
