/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co.com.accenture.certificacion.despegar;

import org.junit.Test;

import co.com.accenture.certificacion.despegar.Library;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
